name: Build KeyFlare executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # latest python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Run build script on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile --noconsole keyflare/keyflare.py
      - name: Run build script on Windows
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --noconsole --windowed keyflare/keyflare.py
      - name: Run build script on macOS
        if: matrix.os == 'macOS-latest'
        run: |
          pyinstaller --onefile --noconsole --windowed --osx-bundle-identifier "com.example.yourapp" keyflare/keyflare.py
      - name: Upload artifacts for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: keyflare-${{ matrix.os }}
          path: dist/keyflare
      - name: Upload artifacts for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: keyflare-${{ matrix.os }}
          path: dist/keyflare.exe
      - name: Upload artifacts for macOS
        if: matrix.os == 'macOS-latest'
        uses: actions/upload-artifact@v2
        with:
          name: keyflare-${{ matrix.os }}
          path: dist/keyflare.app
